CREATE TABLE IF NOT EXISTS tweets (
   tweet_id BIGINT UNIQUE,
   id  SERIAL PRIMARY KEY,
   created_on TIMESTAMP,
   date TIMESTAMP,
   text TEXT,
   twitter_user_id BIGINT REFERENCES users (twitter_id),
   is_retweet BOOLEAN,
   retweeted_tweet_id BIGINT,
   is_quoted BOOLEAN,
   quoted_tweet_id BIGINT,
   is_reply BOOLEAN,
   is_sensitive BOOLEAN,
   reply_counts INT,
   quote_counts INT,
   replied_to_tweet_id BIGINT,
   bookmark_count INT,
   views INT,
   likes INT,
   language TEXT,
   retweet_counts INT,
   source TEXT,
   audio_space_twitter_id BIGINT,
   community_note TEXT,
   url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
