CREATE TABLE IF NOT EXISTS users
(
    user_id                 SERIAL PRIMARY KEY,
    twitter_id              BIGINT UNIQUE,
    rest_id                 BIGINT NOT NULL,
    twitter_created_at      TIMESTAMP,
    date                    TIMESTAMP,
    description             TEXT,
    bio                     TEXT,
    entities                JSONB,
    fast_followers_count    INT,
    favourites_count        INT,
    followers_count         INT,
    friends_count           INT,
    listed_count            INT,
    location                TEXT,
    media_count             INT,
    name                    TEXT,
    normal_followers_count  INT,
    profile_banner_url      TEXT,
    profile_image_url_https TEXT,
    protected               BOOLEAN,
    screen_name             TEXT,
    username                TEXT,
    statuses_count          INT,
    verified                BOOLEAN,
    pinned_tweets           TEXT[],
    community_role          TEXT,
    categories              TEXT[],
    last_fetched            TIMESTAMP,
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
